
development:
  adapter: postgres
  database: drugplants_development
  pool: 5
  timeout: 5000

test:
  adapter: postgres
  database: drugplants_test
  pool: 5
  timeout: 5000

production:
  adapter: postgres
  database: drugplants_production
  pool: 5
  timeout: 5000
